import {TemplateInterface} from './../../TemplateInterface';
const html = require('common-tags').html;

/**
 * create the RelutionHjson file for the Project
 * @link [template](https://github.com/github/gitignore/blob/master/Node.gitignore)
 */
export class GitIgnore implements TemplateInterface {

  public publishName: string = '.gitignore';
  public name: string = 'gitignore';

  get template() {
    return (html`
      # Logs
      logs
      *.log
      npm-debug.log*

      # Runtime data
      pids
      *.pid
      *.seed

      # Directory for instrumented libs generated by jscoverage/JSCover
      lib-cov

      # Coverage directory used by tools like istanbul
      coverage

      # nyc test coverage
      .nyc_output

      # Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
      .grunt

      # node-waf configuration
      .lock-wscript

      # Compiled binary addons (http://nodejs.org/api/addons.html)
      build/Release

      # Dependency directories
      node_modules
      jspm_packages

      # Optional npm cache directory
      .npm

      # Optional REPL history
      .node_repl_history
    `);
  }
}
