"use strict";
var chalk = require('chalk');
var path = require('path');
var figures = require('figures');
var lodash_1 = require('lodash');
var rxjs_1 = require('@reactivex/rxjs');
var Relution = require('relution-sdk');
var FileApi_1 = require('../../utility/FileApi');
var RxFs_1 = require('../../utility/RxFs');
var Archiver_1 = require('../../utility/Archiver');
var DebugLog_1 = require('../../utility/DebugLog');
var loader = require('cli-loader')();
/**
 * ```bash
 * ┌─────────┬──────────┬──────────┬────────────────────────────────┐
 * │ Options │ Commands │ Param(s) │ Description                    │
 * │         │          │          │                                │
 * │ deploy  │ deploy   │ <$name>  │ deploy your Baas to the server │
 * │ deploy  │ help     │ --       │ List the Deploy Command        │
 * │ deploy  │ back     │ --       │ Exit to Home                   │
 * │         │          │          │                                │
 * └─────────┴──────────┴──────────┴────────────────────────────────┘
 * ```
 * @todo remove zip file after deploy
 */
var Deploy = (function () {
    function Deploy(owner) {
        this.debuglog = DebugLog_1.DebugLog;
        this._promptkey = 'deployserver';
        this._defaultServer = 'default';
        this._archiver = new Archiver_1.Archiver();
        this._fileApi = new FileApi_1.FileApi();
        this.owner = owner;
        this.userRc = owner.userRc;
        this.i18n = owner.i18n;
        this.relutionSDK = owner.relutionSDK;
        this.debuglog = owner.debuglog;
        this.inquirer = owner.inquirer;
    }
    Deploy.prototype._copy = function (org) {
        return JSON.parse(JSON.stringify(org));
    };
    Deploy.prototype._getServers = function () {
        var _this = this;
        this._defaultServer = 'default';
        return this.userRc.streamRc().exhaustMap(function () {
            var prompt = _this._copy(_this.owner._parent.staticCommands.server.crudHelper.serverListPrompt(_this._promptkey, 'list', 'Select a Server'));
            var indexDefault = lodash_1.findIndex(_this.userRc.server, { default: true });
            if (indexDefault > -1) {
                _this._defaultServer += " " + prompt[0].choices[indexDefault];
                prompt[0].choices.splice(indexDefault, 1);
                prompt[0].choices.unshift(_this._defaultServer);
            }
            return prompt;
        });
    };
    /**
     * choose first on which Server the App has to be deployed
     */
    Deploy.prototype.getServerPrompt = function () {
        var _this = this;
        this._defaultServer = 'default';
        return this._getServers().exhaustMap(function (prompt) {
            return rxjs_1.Observable.fromPromise(_this.inquirer.prompt(prompt));
        });
    };
    /**
     * Get the organisation and test if it has defaultRoles. If not raise an error. If an application is generated by a user in a group that has no defaultRoles the application
     * doesn't work as expected.
     */
    Deploy.prototype.checkOrga = function (resp) {
        var orga = Relution.security.getCurrentOrganization('defaultRoles');
        return orga && orga.defaultRoles && orga.defaultRoles.length > 0;
    };
    /**
     * upload the generated zip to the server
     */
    Deploy.prototype.upload = function (archiveresp, env) {
        var _this = this;
        loader.start();
        // data to upload
        var formData = {
            // Pass a simple key-value pair
            name: this._relutionHjson.name,
            uuid: this._relutionHjson.uuid,
            // Pass optional meta-data with an 'options' object with style: {value: DATA, options: OPTIONS}
            // Use case: for some types of streams, you'll need to provide 'file'-related information manually.
            // See the `form-data` README for more information about options: https://github.com/form-data/form-data
            custom_file: {
                value: archiveresp.readStream,
                options: {
                    filename: path.basename(archiveresp.zip),
                    contentType: 'application/zip'
                }
            }
        };
        if (env) {
            // env key/value is present only if an environment was choosen
            formData.env = env;
        }
        // continuously queries deployment status if server supports this
        var deploymentUrl;
        var deploymentCheck = function (response) {
            if (!deploymentUrl) {
                return response;
            }
            var statusCode;
            return Relution.web.get({
                url: deploymentUrl,
                responseCallback: function (resp) {
                    statusCode = resp.statusCode;
                    return resp;
                }
            }).then(function (body) {
                if (statusCode === 202) {
                    // deployment ongoing, repeat request
                    Relution.debug.assert(!body);
                    return deploymentCheck(response);
                }
                return response;
            }, function (error) {
                if (error && error.statusCode === 404) {
                    // relution server does not support deployment status query
                    return response;
                }
                throw error;
            });
        };
        return rxjs_1.Observable.fromPromise(Relution.web.ajax({
            url: 'upload',
            headers: {
                'Accept': 'text/plain'
            },
            method: 'POST',
            formData: formData,
            requestCallback: function (request) {
                request.once('data', function () { return loader.stop(); });
                request.pipe(process.stdout, { 'end': false });
                return request;
            },
            responseCallback: function (response) {
                deploymentUrl = response.headers['X-Relution-Studio-Deployment-Url'.toLowerCase()];
                return response;
            }
        })
            .finally(function () { return loader.start(); })
            .then(deploymentCheck)
            .finally(function () { return loader.stop(); })
            .then(function (result) {
            _this.debuglog.info(_this.i18n.DEPLOY_SUCCESS);
            // be nice and output URL of application
            var url = Relution.web.resolveApp(_this._relutionHjson);
            if (url) {
                _this.debuglog.info(_this.i18n.DEPLOY_APPURL, url);
            }
            return result;
        }, function (error) {
            _this.debuglog.error(new Error(_this.i18n.DEPLOY_FAILED));
            throw error;
        }));
    };
    /**
     * deploy the baas to the server
     */
    Deploy.prototype.publish = function (args) {
        var _this = this;
        var serverArgName = undefined;
        if (args && args[0]) {
            serverArgName = args[0];
        }
        this._fileApi.path = this.projectDir;
        // loginresponse
        var userResp;
        // choosed environment
        var envName = undefined;
        // choosed Server
        var choosedServer;
        if (!RxFs_1.RxFs.exist(path.join(process.cwd(), 'relution.hjson')) || !RxFs_1.RxFs.exist(path.join(process.cwd(), '.relutionignore'))) {
            return rxjs_1.Observable.throw(new Error(process.cwd() + " is not a valid Relution Project"));
        }
        // load the environments before
        return this.owner._parent.staticCommands.env.envCollection.getEnvironments()
            .map(function () {
            if (args && args[1]) {
                var exists = lodash_1.find(_this.owner._parent.staticCommands.env.envCollection.collection, { name: args[1] });
                if (exists) {
                    envName = exists.name;
                }
                else {
                    _this.debuglog.warn(_this.i18n.DEPLOY_ENV_NOT_EXISTS(args[1]));
                }
            }
        })
            .exhaustMap(function () {
            return _this._fileApi.readHjson(path.join(_this.projectDir, 'relution.hjson'));
        })
            .exhaustMap(function (relutionHjson) {
            _this._relutionHjson = relutionHjson.data;
            if (!serverArgName) {
                return _this.getServerPrompt();
            }
            return _this._getServers().map(function () {
                return { deployserver: serverArgName };
            });
        })
            .filter(function (server) {
            return server.deployserver !== _this.i18n.CANCEL;
        })
            .exhaustMap(function (server) {
            if (server.deployserver.toString().trim() === _this._defaultServer.toString().trim()) {
                choosedServer = lodash_1.find(_this.userRc.server, { default: true });
            }
            else {
                choosedServer = lodash_1.find(_this.userRc.server, { id: server.deployserver });
            }
            loader.start();
            return _this.relutionSDK.login(choosedServer);
        })
            .exhaustMap(function (resp) {
            userResp = resp.user;
            loader.stop();
            if (!_this.checkOrga(userResp)) {
                return rxjs_1.Observable.throw(new Error(_this.i18n.DEPLOY_NO_ORGA));
            }
            _this.debuglog.info(chalk.green("Login as " + (userResp.givenName ? userResp.givenName + ' ' + userResp.surname : userResp.name) + " succeeded. " + figures.tick));
            if (_this.owner._parent.staticCommands.env.chooseEnv.envCollection.collection.length && !envName) {
                // must choose an environment
                return _this.owner._parent.staticCommands.env.chooseEnv.choose('list')
                    .filter(function (answers) {
                    return answers.env !== _this.i18n.CANCEL;
                })
                    .map(function (answers) {
                    envName = answers[_this.owner._parent.staticCommands.env.chooseEnv.promptName];
                    return _this._archiver.createBundle();
                });
            }
            else {
                // there is no environment present
                return rxjs_1.Observable.of(_this._archiver.createBundle());
            }
        })
            .exhaustMap(function (log) {
            return log.map(function (respLog) {
                if (respLog.file || respLog.directory) {
                    _this.debuglog.info(chalk.magenta(respLog.file ? "add file " + respLog.file : "add directory " + respLog.directory));
                }
                else if (respLog.processed) {
                    _this.debuglog.info(chalk.green(respLog.processed) + ' ' + figures.tick);
                }
                return respLog;
            })
                .filter(function (respLog) {
                return respLog['zip'];
            });
        })
            .exhaustMap(function (respLog) {
            _this.debuglog.info(chalk.green(respLog.message) + ' ' + figures.tick);
            return _this.upload(respLog, envName);
        })
            .ignoreElements() // log piped already
            .finally(function () {
            loader.stop();
        }).do({
            error: function () {
                // is directly used
                if (args && args[0] && args[1]) {
                    process.exit(-1);
                }
            },
            complete: function () {
                // is directly used
                if (args && args[0] && args[1]) {
                    process.exit(0);
                }
            }
        });
    };
    Object.defineProperty(Deploy.prototype, "projectDir", {
        get: function () {
            if (!this._projectDir) {
                this._projectDir = process.cwd();
            }
            return this._projectDir;
        },
        set: function (v) {
            this._projectDir = v;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(Deploy.prototype, "relutionHjson", {
        get: function () {
            return this._relutionHjson;
        },
        set: function (v) {
            this._relutionHjson = v;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(Deploy.prototype, "defaultServer", {
        get: function () {
            return this._defaultServer;
        },
        enumerable: true,
        configurable: true
    });
    return Deploy;
}());
exports.Deploy = Deploy;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGVwbG95LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiLi4vLi4vLi4vc3JjL2NvbW1hbmRzL3Byb2plY3QvRGVwbG95LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxJQUFZLEtBQUssV0FBTSxPQUFPLENBQUMsQ0FBQTtBQUMvQixJQUFZLElBQUksV0FBTSxNQUFNLENBQUMsQ0FBQTtBQUM3QixJQUFNLE9BQU8sR0FBRyxPQUFPLENBQUMsU0FBUyxDQUFDLENBQUM7QUFFbkMsdUJBQThCLFFBQVEsQ0FBQyxDQUFBO0FBQ3ZDLHFCQUF5QixpQkFBaUIsQ0FBQyxDQUFBO0FBQzNDLElBQVksUUFBUSxXQUFNLGNBQWMsQ0FBQyxDQUFBO0FBQ3pDLHdCQUFzQix1QkFBdUIsQ0FBQyxDQUFBO0FBQzlDLHFCQUFtQixvQkFBb0IsQ0FBQyxDQUFBO0FBQ3hDLHlCQUF1Qix3QkFBd0IsQ0FBQyxDQUFBO0FBR2hELHlCQUF1Qix3QkFBd0IsQ0FBQyxDQUFBO0FBSWhELElBQU0sTUFBTSxHQUFHLE9BQU8sQ0FBQyxZQUFZLENBQUMsRUFBRSxDQUFDO0FBQ3ZDOzs7Ozs7Ozs7Ozs7R0FZRztBQUNIO0lBZUUsZ0JBQVksS0FBYztRQVZsQixhQUFRLEdBQUcsbUJBQVEsQ0FBQztRQUdwQixlQUFVLEdBQVcsY0FBYyxDQUFDO1FBQ3BDLG1CQUFjLEdBQVcsU0FBUyxDQUFDO1FBQ25DLGNBQVMsR0FBYSxJQUFJLG1CQUFRLEVBQUUsQ0FBQztRQUdyQyxhQUFRLEdBQVksSUFBSSxpQkFBTyxFQUFFLENBQUM7UUFHeEMsSUFBSSxDQUFDLEtBQUssR0FBRyxLQUFLLENBQUM7UUFDbkIsSUFBSSxDQUFDLE1BQU0sR0FBRyxLQUFLLENBQUMsTUFBTSxDQUFDO1FBQzNCLElBQUksQ0FBQyxJQUFJLEdBQUcsS0FBSyxDQUFDLElBQUksQ0FBQztRQUN2QixJQUFJLENBQUMsV0FBVyxHQUFHLEtBQUssQ0FBQyxXQUFXLENBQUM7UUFDckMsSUFBSSxDQUFDLFFBQVEsR0FBRyxLQUFLLENBQUMsUUFBUSxDQUFDO1FBQy9CLElBQUksQ0FBQyxRQUFRLEdBQUcsS0FBSyxDQUFDLFFBQVEsQ0FBQztJQUNqQyxDQUFDO0lBRUQsc0JBQUssR0FBTCxVQUFNLEdBQVE7UUFDWixNQUFNLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUM7SUFDekMsQ0FBQztJQUVELDRCQUFXLEdBQVg7UUFBQSxpQkFhQztRQVpDLElBQUksQ0FBQyxjQUFjLEdBQUcsU0FBUyxDQUFDO1FBQ2hDLE1BQU0sQ0FBQyxJQUFJLENBQUMsTUFBTSxDQUFDLFFBQVEsRUFBRSxDQUFDLFVBQVUsQ0FBQztZQUN2QyxJQUFJLE1BQU0sR0FBRyxLQUFJLENBQUMsS0FBSyxDQUFDLEtBQUksQ0FBQyxLQUFLLENBQUMsT0FBTyxDQUFDLGNBQWMsQ0FBQyxNQUFNLENBQUMsVUFBVSxDQUFDLGdCQUFnQixDQUFDLEtBQUksQ0FBQyxVQUFVLEVBQUUsTUFBTSxFQUFFLGlCQUFpQixDQUFDLENBQUMsQ0FBQztZQUMxSSxJQUFJLFlBQVksR0FBVyxrQkFBUyxDQUFDLEtBQUksQ0FBQyxNQUFNLENBQUMsTUFBTSxFQUFFLEVBQUUsT0FBTyxFQUFFLElBQUksRUFBRSxDQUFDLENBQUM7WUFFNUUsRUFBRSxDQUFDLENBQUMsWUFBWSxHQUFHLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztnQkFDdEIsS0FBSSxDQUFDLGNBQWMsSUFBSSxNQUFJLE1BQU0sQ0FBQyxDQUFDLENBQUMsQ0FBQyxPQUFPLENBQUMsWUFBWSxDQUFHLENBQUM7Z0JBQzdELE1BQU0sQ0FBQyxDQUFDLENBQUMsQ0FBQyxPQUFPLENBQUMsTUFBTSxDQUFDLFlBQVksRUFBRSxDQUFDLENBQUMsQ0FBQztnQkFDMUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsS0FBSSxDQUFDLGNBQWMsQ0FBQyxDQUFDO1lBQ2pELENBQUM7WUFDRCxNQUFNLENBQUMsTUFBTSxDQUFDO1FBQ2hCLENBQUMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUNEOztPQUVHO0lBQ0gsZ0NBQWUsR0FBZjtRQUFBLGlCQUtDO1FBSkMsSUFBSSxDQUFDLGNBQWMsR0FBRyxTQUFTLENBQUM7UUFDaEMsTUFBTSxDQUFDLElBQUksQ0FBQyxXQUFXLEVBQUUsQ0FBQyxVQUFVLENBQUMsVUFBQyxNQUFNO1lBQzFDLE1BQU0sQ0FBQyxpQkFBVSxDQUFDLFdBQVcsQ0FBQyxLQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDO1FBQzlELENBQUMsQ0FBQyxDQUFDO0lBQ0wsQ0FBQztJQUVEOzs7T0FHRztJQUNILDBCQUFTLEdBQVQsVUFBVSxJQUFTO1FBQ2pCLElBQUksSUFBSSxHQUFRLFFBQVEsQ0FBQyxRQUFRLENBQUMsc0JBQXNCLENBQUMsY0FBYyxDQUFDLENBQUM7UUFDekUsTUFBTSxDQUFDLElBQUksSUFBSSxJQUFJLENBQUMsWUFBWSxJQUFJLElBQUksQ0FBQyxZQUFZLENBQUMsTUFBTSxHQUFHLENBQUMsQ0FBQztJQUNuRSxDQUFDO0lBRUQ7O09BRUc7SUFDSCx1QkFBTSxHQUFOLFVBQU8sV0FBZ0IsRUFBRSxHQUFXO1FBQXBDLGlCQXdGQztRQXZGQyxNQUFNLENBQUMsS0FBSyxFQUFFLENBQUM7UUFDZixpQkFBaUI7UUFDakIsSUFBSSxRQUFRLEdBQVE7WUFDbEIsK0JBQStCO1lBQy9CLElBQUksRUFBRSxJQUFJLENBQUMsY0FBYyxDQUFDLElBQUk7WUFDOUIsSUFBSSxFQUFFLElBQUksQ0FBQyxjQUFjLENBQUMsSUFBSTtZQUM5QiwrRkFBK0Y7WUFDL0YsbUdBQW1HO1lBQ25HLHdHQUF3RztZQUN4RyxXQUFXLEVBQUU7Z0JBQ1gsS0FBSyxFQUFFLFdBQVcsQ0FBQyxVQUFVO2dCQUM3QixPQUFPLEVBQUU7b0JBQ1AsUUFBUSxFQUFFLElBQUksQ0FBQyxRQUFRLENBQUMsV0FBVyxDQUFDLEdBQUcsQ0FBQztvQkFDeEMsV0FBVyxFQUFFLGlCQUFpQjtpQkFDL0I7YUFDRjtTQUNGLENBQUM7UUFDRixFQUFFLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxDQUFDO1lBQ1IsOERBQThEO1lBQzlELFFBQVEsQ0FBQyxHQUFHLEdBQUcsR0FBRyxDQUFDO1FBQ3JCLENBQUM7UUFFRCxpRUFBaUU7UUFDakUsSUFBSSxhQUFxQixDQUFDO1FBQzFCLElBQUksZUFBZSxHQUFHLFVBQUMsUUFBYTtZQUNsQyxFQUFFLENBQUMsQ0FBQyxDQUFDLGFBQWEsQ0FBQyxDQUFDLENBQUM7Z0JBQ25CLE1BQU0sQ0FBQyxRQUFRLENBQUM7WUFDbEIsQ0FBQztZQUVELElBQUksVUFBa0IsQ0FBQztZQUN2QixNQUFNLENBQUMsUUFBUSxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUM7Z0JBQ3RCLEdBQUcsRUFBRSxhQUFhO2dCQUNsQixnQkFBZ0IsRUFBRSxVQUFDLElBQStCO29CQUNoRCxVQUFVLEdBQUcsSUFBSSxDQUFDLFVBQVUsQ0FBQztvQkFDN0IsTUFBTSxDQUFDLElBQUksQ0FBQztnQkFDZCxDQUFDO2FBQ0YsQ0FBQyxDQUFDLElBQUksQ0FBQyxVQUFDLElBQUk7Z0JBQ1gsRUFBRSxDQUFDLENBQUMsVUFBVSxLQUFLLEdBQUcsQ0FBQyxDQUFDLENBQUM7b0JBQ3ZCLHFDQUFxQztvQkFDckMsUUFBUSxDQUFDLEtBQUssQ0FBQyxNQUFNLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQztvQkFDN0IsTUFBTSxDQUFDLGVBQWUsQ0FBQyxRQUFRLENBQUMsQ0FBQztnQkFDbkMsQ0FBQztnQkFDRCxNQUFNLENBQUMsUUFBUSxDQUFDO1lBQ2xCLENBQUMsRUFBRSxVQUFDLEtBQTZCO2dCQUMvQixFQUFFLENBQUMsQ0FBQyxLQUFLLElBQUksS0FBSyxDQUFDLFVBQVUsS0FBSyxHQUFHLENBQUMsQ0FBQyxDQUFDO29CQUN0QywyREFBMkQ7b0JBQzNELE1BQU0sQ0FBQyxRQUFRLENBQUM7Z0JBQ2xCLENBQUM7Z0JBQ0QsTUFBTSxLQUFLLENBQUM7WUFDZCxDQUFDLENBQUMsQ0FBQztRQUNMLENBQUMsQ0FBQztRQUVGLE1BQU0sQ0FBQyxpQkFBVSxDQUFDLFdBQVcsQ0FDM0IsUUFBUSxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUM7WUFDaEIsR0FBRyxFQUFFLFFBQVE7WUFDYixPQUFPLEVBQUU7Z0JBQ1AsUUFBUSxFQUFFLFlBQVk7YUFDdkI7WUFDRCxNQUFNLEVBQUUsTUFBTTtZQUNkLFFBQVEsRUFBRSxRQUFRO1lBQ2xCLGVBQWUsRUFBRSxVQUFDLE9BQWlDO2dCQUNqRCxPQUFPLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxjQUFNLE9BQUEsTUFBTSxDQUFDLElBQUksRUFBRSxFQUFiLENBQWEsQ0FBQyxDQUFDO2dCQUMxQyxPQUFPLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxNQUFNLEVBQUUsRUFBRSxLQUFLLEVBQUUsS0FBSyxFQUFFLENBQUMsQ0FBQztnQkFDL0MsTUFBTSxDQUFDLE9BQU8sQ0FBQztZQUNqQixDQUFDO1lBQ0QsZ0JBQWdCLEVBQUUsVUFBQyxRQUFtQztnQkFDcEQsYUFBYSxHQUFHLFFBQVEsQ0FBQyxPQUFPLENBQUMsa0NBQWtDLENBQUMsV0FBVyxFQUFFLENBQUMsQ0FBQztnQkFDbkYsTUFBTSxDQUFDLFFBQVEsQ0FBQztZQUNsQixDQUFDO1NBQ0YsQ0FBQzthQUNELE9BQU8sQ0FBQyxjQUFNLE9BQUEsTUFBTSxDQUFDLEtBQUssRUFBRSxFQUFkLENBQWMsQ0FBQzthQUM3QixJQUFJLENBQUMsZUFBZSxDQUFDO2FBQ3JCLE9BQU8sQ0FBQyxjQUFNLE9BQUEsTUFBTSxDQUFDLElBQUksRUFBRSxFQUFiLENBQWEsQ0FBQzthQUM1QixJQUFJLENBQUMsVUFBQyxNQUFNO1lBQ1gsS0FBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsS0FBSSxDQUFDLElBQUksQ0FBQyxjQUFjLENBQUMsQ0FBQztZQUU3Qyx3Q0FBd0M7WUFDeEMsSUFBTSxHQUFHLEdBQUcsUUFBUSxDQUFDLEdBQUcsQ0FBQyxVQUFVLENBQUMsS0FBSSxDQUFDLGNBQWMsQ0FBQyxDQUFDO1lBQ3pELEVBQUUsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUM7Z0JBQ1IsS0FBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsS0FBSSxDQUFDLElBQUksQ0FBQyxhQUFhLEVBQUUsR0FBRyxDQUFDLENBQUM7WUFDbkQsQ0FBQztZQUNELE1BQU0sQ0FBQyxNQUFNLENBQUM7UUFDaEIsQ0FBQyxFQUFFLFVBQUMsS0FBNkI7WUFDL0IsS0FBSSxDQUFDLFFBQVEsQ0FBQyxLQUFLLENBQUMsSUFBSSxLQUFLLENBQUMsS0FBSSxDQUFDLElBQUksQ0FBQyxhQUFhLENBQUMsQ0FBQyxDQUFDO1lBQ3hELE1BQU0sS0FBSyxDQUFDO1FBQ2QsQ0FBQyxDQUFDLENBQ0gsQ0FBQztJQUNKLENBQUM7SUFFRDs7T0FFRztJQUNJLHdCQUFPLEdBQWQsVUFBZSxJQUFvQjtRQUFuQyxpQkEySUM7UUExSUMsSUFBSSxhQUFhLEdBQVEsU0FBUyxDQUFDO1FBRW5DLEVBQUUsQ0FBQyxDQUFDLElBQUksSUFBSSxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1lBQ3BCLGFBQWEsR0FBRyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFDMUIsQ0FBQztRQUVELElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxHQUFHLElBQUksQ0FBQyxVQUFVLENBQUM7UUFFckMsZ0JBQWdCO1FBQ2hCLElBQUksUUFBZ0MsQ0FBQztRQUVyQyxzQkFBc0I7UUFDdEIsSUFBSSxPQUFPLEdBQVEsU0FBUyxDQUFDO1FBRTdCLGlCQUFpQjtRQUNqQixJQUFJLGFBQWtCLENBQUM7UUFFdkIsRUFBRSxDQUFDLENBQUMsQ0FBQyxXQUFJLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLEdBQUcsRUFBRSxFQUFFLGdCQUFnQixDQUFDLENBQUMsSUFBSSxDQUFDLFdBQUksQ0FBQyxLQUFLLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsR0FBRyxFQUFFLEVBQUUsaUJBQWlCLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztZQUN4SCxNQUFNLENBQUMsaUJBQVUsQ0FBQyxLQUFLLENBQUMsSUFBSSxLQUFLLENBQUksT0FBTyxDQUFDLEdBQUcsRUFBRSxxQ0FBa0MsQ0FBQyxDQUFDLENBQUM7UUFDekYsQ0FBQztRQUNELCtCQUErQjtRQUMvQixNQUFNLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQUMsY0FBYyxDQUFDLEdBQUcsQ0FBQyxhQUFhLENBQUMsZUFBZSxFQUFFO2FBQ3pFLEdBQUcsQ0FBQztZQUNILEVBQUUsQ0FBQyxDQUFDLElBQUksSUFBSSxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO2dCQUNwQixJQUFNLE1BQU0sR0FBRyxhQUFJLENBQUMsS0FBSSxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQUMsY0FBYyxDQUFDLEdBQUcsQ0FBQyxhQUFhLENBQUMsVUFBVSxFQUFFLEVBQUMsSUFBSSxFQUFFLElBQUksQ0FBQyxDQUFDLENBQUMsRUFBQyxDQUFDLENBQUM7Z0JBQ3JHLEVBQUUsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUM7b0JBQ1gsT0FBTyxHQUFHLE1BQU0sQ0FBQyxJQUFJLENBQUM7Z0JBQ3hCLENBQUM7Z0JBQUMsSUFBSSxDQUFDLENBQUM7b0JBQ04sS0FBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsS0FBSSxDQUFDLElBQUksQ0FBQyxxQkFBcUIsQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO2dCQUMvRCxDQUFDO1lBQ0gsQ0FBQztRQUNILENBQUMsQ0FBQzthQUlELFVBQVUsQ0FBQztZQUNWLE1BQU0sQ0FBQyxLQUFJLENBQUMsUUFBUSxDQUFDLFNBQVMsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUksQ0FBQyxVQUFVLEVBQUUsZ0JBQWdCLENBQUMsQ0FBQyxDQUFDO1FBQy9FLENBQUMsQ0FBQzthQUlELFVBQVUsQ0FBQyxVQUFDLGFBQTBDO1lBQ3JELEtBQUksQ0FBQyxjQUFjLEdBQUcsYUFBYSxDQUFDLElBQUksQ0FBQztZQUN6QyxFQUFFLENBQUMsQ0FBQyxDQUFDLGFBQWEsQ0FBQyxDQUFDLENBQUM7Z0JBQ25CLE1BQU0sQ0FBQyxLQUFJLENBQUMsZUFBZSxFQUFFLENBQUM7WUFDaEMsQ0FBQztZQUNELE1BQU0sQ0FBQyxLQUFJLENBQUMsV0FBVyxFQUFFLENBQUMsR0FBRyxDQUFDO2dCQUM1QixNQUFNLENBQUMsRUFBRSxZQUFZLEVBQUUsYUFBYSxFQUFFLENBQUM7WUFDekMsQ0FBQyxDQUFDLENBQUM7UUFDTCxDQUFDLENBQUM7YUFDRCxNQUFNLENBQUMsVUFBQyxNQUFnQztZQUN2QyxNQUFNLENBQUMsTUFBTSxDQUFDLFlBQVksS0FBSyxLQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sQ0FBQztRQUNsRCxDQUFDLENBQUM7YUFJRCxVQUFVLENBQUMsVUFBQyxNQUFnQztZQUMzQyxFQUFFLENBQUMsQ0FBQyxNQUFNLENBQUMsWUFBWSxDQUFDLFFBQVEsRUFBRSxDQUFDLElBQUksRUFBRSxLQUFLLEtBQUksQ0FBQyxjQUFjLENBQUMsUUFBUSxFQUFFLENBQUMsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO2dCQUNwRixhQUFhLEdBQUcsYUFBSSxDQUFDLEtBQUksQ0FBQyxNQUFNLENBQUMsTUFBTSxFQUFFLEVBQUUsT0FBTyxFQUFFLElBQUksRUFBRSxDQUFDLENBQUM7WUFDOUQsQ0FBQztZQUFDLElBQUksQ0FBQyxDQUFDO2dCQUNOLGFBQWEsR0FBRyxhQUFJLENBQUMsS0FBSSxDQUFDLE1BQU0sQ0FBQyxNQUFNLEVBQUUsRUFBRSxFQUFFLEVBQUUsTUFBTSxDQUFDLFlBQVksRUFBRSxDQUFDLENBQUM7WUFDeEUsQ0FBQztZQUNELE1BQU0sQ0FBQyxLQUFLLEVBQUUsQ0FBQztZQUNmLE1BQU0sQ0FBQyxLQUFJLENBQUMsV0FBVyxDQUFDLEtBQUssQ0FBQyxhQUFhLENBQUMsQ0FBQztRQUMvQyxDQUFDLENBQUM7YUFJRCxVQUFVLENBQUMsVUFBQyxJQUFTO1lBQ3BCLFFBQVEsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDO1lBQ3JCLE1BQU0sQ0FBQyxJQUFJLEVBQUUsQ0FBQztZQUNkLEVBQUUsQ0FBQyxDQUFDLENBQUMsS0FBSSxDQUFDLFNBQVMsQ0FBQyxRQUFRLENBQUMsQ0FBQyxDQUFDLENBQUM7Z0JBQzlCLE1BQU0sQ0FBQyxpQkFBVSxDQUFDLEtBQUssQ0FBQyxJQUFJLEtBQUssQ0FBQyxLQUFJLENBQUMsSUFBSSxDQUFDLGNBQWMsQ0FBQyxDQUFDLENBQUM7WUFDL0QsQ0FBQztZQUNELEtBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQUMsZUFBWSxRQUFRLENBQUMsU0FBUyxHQUFHLFFBQVEsQ0FBQyxTQUFTLEdBQUcsR0FBRyxHQUFHLFFBQVEsQ0FBQyxPQUFPLEdBQUcsUUFBUSxDQUFDLElBQUkscUJBQWUsT0FBTyxDQUFDLElBQU0sQ0FBQyxDQUFDLENBQUM7WUFFM0osRUFBRSxDQUFDLENBQUMsS0FBSSxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQUMsY0FBYyxDQUFDLEdBQUcsQ0FBQyxTQUFTLENBQUMsYUFBYSxDQUFDLFVBQVUsQ0FBQyxNQUFNLElBQUksQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDO2dCQUNoRyw2QkFBNkI7Z0JBQzdCLE1BQU0sQ0FBQyxLQUFJLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBQyxjQUFjLENBQUMsR0FBRyxDQUFDLFNBQVMsQ0FBQyxNQUFNLENBQUMsTUFBTSxDQUFDO3FCQUNsRSxNQUFNLENBQUMsVUFBQyxPQUF3QjtvQkFDL0IsTUFBTSxDQUFDLE9BQU8sQ0FBQyxHQUFHLEtBQUssS0FBSSxDQUFDLElBQUksQ0FBQyxNQUFNLENBQUM7Z0JBQzFDLENBQUMsQ0FBQztxQkFJRCxHQUFHLENBQUMsVUFBQyxPQUF3QjtvQkFDNUIsT0FBTyxHQUFHLE9BQU8sQ0FBQyxLQUFJLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBQyxjQUFjLENBQUMsR0FBRyxDQUFDLFNBQVMsQ0FBQyxVQUFVLENBQUMsQ0FBQztvQkFDOUUsTUFBTSxDQUFDLEtBQUksQ0FBQyxTQUFTLENBQUMsWUFBWSxFQUFFLENBQUM7Z0JBQ3ZDLENBQUMsQ0FBQyxDQUFDO1lBQ1AsQ0FBQztZQUFDLElBQUksQ0FBQyxDQUFDO2dCQUNOLGtDQUFrQztnQkFDbEMsTUFBTSxDQUFDLGlCQUFVLENBQUMsRUFBRSxDQUFDLEtBQUksQ0FBQyxTQUFTLENBQUMsWUFBWSxFQUFFLENBQUMsQ0FBQztZQUN0RCxDQUFDO1FBQ0gsQ0FBQyxDQUFDO2FBSUQsVUFBVSxDQUFDLFVBQUMsR0FBNkc7WUFDeEgsTUFBTSxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsVUFBQyxPQUFZO2dCQUMxQixFQUFFLENBQUMsQ0FBQyxPQUFPLENBQUMsSUFBSSxJQUFJLE9BQU8sQ0FBQyxTQUFTLENBQUMsQ0FBQyxDQUFDO29CQUN0QyxLQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsT0FBTyxDQUFDLE9BQU8sQ0FBQyxJQUFJLEdBQUcsY0FBWSxPQUFPLENBQUMsSUFBTSxHQUFHLG1CQUFpQixPQUFPLENBQUMsU0FBVyxDQUFDLENBQUMsQ0FBQztnQkFDdEgsQ0FBQztnQkFBQyxJQUFJLENBQUMsRUFBRSxDQUFDLENBQUMsT0FBTyxDQUFDLFNBQVMsQ0FBQyxDQUFDLENBQUM7b0JBQzdCLEtBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQUMsT0FBTyxDQUFDLFNBQVMsQ0FBQyxHQUFHLEdBQUcsR0FBRyxPQUFPLENBQUMsSUFBSSxDQUFDLENBQUM7Z0JBQzFFLENBQUM7Z0JBQ0QsTUFBTSxDQUFDLE9BQU8sQ0FBQztZQUNqQixDQUFDLENBQUM7aUJBQ0MsTUFBTSxDQUFDLFVBQUMsT0FBcUc7Z0JBQzVHLE1BQU0sQ0FBQyxPQUFPLENBQUMsS0FBSyxDQUFDLENBQUM7WUFDeEIsQ0FBQyxDQUFDLENBQUM7UUFDUCxDQUFDLENBQUM7YUFJRCxVQUFVLENBQUMsVUFBQyxPQUEwRDtZQUNyRSxLQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsR0FBRyxHQUFHLEdBQUcsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDO1lBQ3RFLE1BQU0sQ0FBQyxLQUFJLENBQUMsTUFBTSxDQUFDLE9BQU8sRUFBRSxPQUFPLENBQUMsQ0FBQztRQUN2QyxDQUFDLENBQUM7YUFLRCxjQUFjLEVBQUUsQ0FBQyxvQkFBb0I7YUFDckMsT0FBTyxDQUFDO1lBQ1AsTUFBTSxDQUFDLElBQUksRUFBRSxDQUFDO1FBQ2hCLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQztZQUNKLEtBQUssRUFBRTtnQkFDTCxtQkFBbUI7Z0JBQ25CLEVBQUUsQ0FBQyxDQUFDLElBQUksSUFBSSxJQUFJLENBQUMsQ0FBQyxDQUFDLElBQUksSUFBSSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztvQkFDL0IsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO2dCQUNuQixDQUFDO1lBQ0gsQ0FBQztZQUNELFFBQVEsRUFBRTtnQkFDUixtQkFBbUI7Z0JBQ25CLEVBQUUsQ0FBQyxDQUFDLElBQUksSUFBSSxJQUFJLENBQUMsQ0FBQyxDQUFDLElBQUksSUFBSSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztvQkFDL0IsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztnQkFDbEIsQ0FBQztZQUNILENBQUM7U0FDRixDQUFDLENBQUM7SUFDUCxDQUFDO0lBRUQsc0JBQVcsOEJBQVU7YUFBckI7WUFDRSxFQUFFLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxXQUFXLENBQUMsQ0FBQyxDQUFDO2dCQUN0QixJQUFJLENBQUMsV0FBVyxHQUFHLE9BQU8sQ0FBQyxHQUFHLEVBQUUsQ0FBQztZQUNuQyxDQUFDO1lBQ0QsTUFBTSxDQUFDLElBQUksQ0FBQyxXQUFXLENBQUM7UUFDMUIsQ0FBQzthQUVELFVBQXNCLENBQVM7WUFDN0IsSUFBSSxDQUFDLFdBQVcsR0FBRyxDQUFDLENBQUM7UUFDdkIsQ0FBQzs7O09BSkE7SUFNRCxzQkFBVyxpQ0FBYTthQUF4QjtZQUNFLE1BQU0sQ0FBQyxJQUFJLENBQUMsY0FBYyxDQUFDO1FBQzdCLENBQUM7YUFFRCxVQUF5QixDQUFNO1lBQzdCLElBQUksQ0FBQyxjQUFjLEdBQUcsQ0FBQyxDQUFDO1FBQzFCLENBQUM7OztPQUpBO0lBS0Qsc0JBQVcsaUNBQWE7YUFBeEI7WUFDRSxNQUFNLENBQUMsSUFBSSxDQUFDLGNBQWMsQ0FBQztRQUM3QixDQUFDOzs7T0FBQTtJQUNILGFBQUM7QUFBRCxDQUFDLEFBL1RELElBK1RDO0FBL1RZLGNBQU0sU0ErVGxCLENBQUEifQ==