"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Command_1 = require('./../utility/Command');
var rxjs_1 = require('@reactivex/rxjs');
var Validator_1 = require('./../utility/Validator');
var Translation_1 = require('./../utility/Translation');
var FileApi_1 = require('./../utility/FileApi');
var Environment_1 = require('./../gii/templates/Environment');
/**
 * create a autogenerated environment for the developer
 * This is a key => value Store for your server project.
 * ```bash
 *  relution env <$name>
 * ```
 */
/**
 * Environment
 */
var Environment = (function (_super) {
    __extends(Environment, _super);
    function Environment() {
        _super.call(this, 'env');
        /**
         * available commands
         */
        this.commands = {
            add: {
                description: 'add a new Environment',
                vars: {
                    name: {
                        pos: 0
                    }
                }
            },
            help: {
                description: 'List the Server Command'
            },
            quit: {
                description: 'Exit To Home'
            }
        };
        /**
         * hjson file helper
         */
        this.fsApi = new FileApi_1.FileApi();
    }
    Environment.prototype.createEnvironment = function (name) {
        var _this = this;
        return rxjs_1.Observable.create(function (observer) {
            var template = new Environment_1.EnvironmentTemplate();
            observer.next(template);
            _this.fsApi.writeHjson(template.render(name), name).subscribe(function (pipe) {
            }, function () { }, function () { return observer.complete; });
        });
    };
    Object.defineProperty(Environment.prototype, "_addName", {
        /**
         * add a name for a new environment
         */
        get: function () {
            return [
                {
                    type: 'input',
                    name: 'name',
                    message: Translation_1.Translation.ENTER_SOMETHING.concat('Environment name'),
                    validate: function (value) {
                        var pass = value.match(Validator_1.Validator.stringPattern);
                        if (pass) {
                            return true;
                        }
                        else {
                            var credential = 'Name';
                            return Translation_1.Translation.NOT_VALID + " " + Translation_1.Translation.ENTER_SOMETHING.concat('Environment name');
                        }
                    }
                }
            ];
        },
        enumerable: true,
        configurable: true
    });
    Environment.prototype.renderEnvironment = function (name) {
    };
    Environment.prototype.enterName = function () {
        var prompt = this._addName;
        return rxjs_1.Observable.fromPromise(this.inquirer.prompt(prompt));
    };
    Environment.prototype.attribute = function () {
    };
    /**
     * add a new Environment
     */
    Environment.prototype.add = function (name) {
        var _this = this;
        if (!name || !name.length) {
            return rxjs_1.Observable.create(function (observer) {
                _this.enterName().subscribe(function (answers) {
                    _this.createEnvironment(answers.name).subscribe({
                        complete: function () { return observer.complete; }
                    });
                }, function (e) { return console.error(e); }, function () { return observer.complete; });
            });
        }
        return rxjs_1.Observable.create(function (observer) {
            _this.createEnvironment(name[0]).subscribe({
                complete: function () { return observer.complete; }
            });
        });
    };
    return Environment;
}(Command_1.Command));
exports.Environment = Environment;
//# sourceMappingURL=Environment.js.map